#!/usr/bin/env bash
# This script configures my Nginx server 
# so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get install -y nginx

#create a html page
#echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

#configure nginx with 301 redirect
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

#restart nginx to apply configuration changes
sudo service nginx restart
