#!/usr/bin/env bash
# manages manage_my_process
# when passing 'start':
# -> creates file containing its PID in /var/run/my_process.id
# -> displays manage_my_process started
# when passing 'stop':
# -> stops manage_my_process
# -> deletes file, /var/run/my_process.pid
# -> deletes manage_my_process stopped
# when passing 'restart':
# -> stops manage_my_process
# -> deletes file, /var/run/my_process.pid
# -> starts manage_my_process
# -> creates a file containing its PID in /var/run/my_process.pid
# -> displays manage_my_process restarted

start_process() {
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
}

stop_process() {
	echo "manage_my_process stopped"
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
}

restart_process() {
	stop_process
	start_process
	echo "manage_my_process restarted"
}

case "$1" in
	start)
		start_process
		;;
	stop)
		stop_process
		;;
	restart)
		restart_process
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
