#!/usr/bin/env bash
# displays Best School 10 times,
# but displays Best School & Hi
# on the 9th iteration
x=0
while [ $x -lt 10 ]
do
	echo "Best School"
	if [ $x -eq 8 ]; then
		echo "Hi"
	fi
	((x++))
done	
