#!/usr/bin/env bash
# This is a shorter version of 1-run_nginx_as_nginx
sed -i '1i\user nginx' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
